services:
  # note: run `xhost +local:docker` on the host to allow Docker to forward X11 to the host
  linux:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    environment:
      - 'DISPLAY'
      - 'PULSE_SERVER'
      - 'WAYLAND_DISPLAY'
      - 'XDG_RUNTIME_DIR'
    network_mode: 'host'
    volumes:
      - './:/home/libui'
      - '$HOME/.Xauthority:/root/.Xauthority'
    working_dir: '/home/libui'

  wsl:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    environment:
      DISPLAY: ':0'
      PULSE_SERVER: '/mnt/wslg/PulseServer'
      WAYLAND_DISPLAY: 'wayland-0'
      XDG_RUNTIME_DIR: '/mnt/wslg/runtime-dir'
    network_mode: 'bridge'
    volumes:
      - './:/home/libui'
      - '/run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix'
      - '/run/desktop/mnt/host/wslg:/mnt/wslg'
    working_dir: '/home/libui'
